//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadiologyImages
    {
        public int ImageID { get; set; }
        public int PatientID { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string PatientIdentityNumber { get; set; }
    
        public virtual TblPatient TblPatient { get; set; }
    }
}
